import 'package:hive_flutter/hive_flutter.dart';
import 'package:scanmate/models/document_model.dart';
import 'package:scanmate/models/folder_model.dart';
import 'package:uuid/uuid.dart';

class StorageService {
  static const String documentsBoxName = 'documents';
  static const String foldersBoxName = 'folders';
  final Uuid _uuid = const Uuid();

  // --- Initialization ---
  static Future<void> initHive() async {
    await Hive.initFlutter(); // Initialize Hive for Flutter

    // Register Adapters - These would be generated by build_runner
    if (!Hive.isAdapterRegistered(DocumentModelAdapter().typeId)) {
      Hive.registerAdapter(DocumentModelAdapter());
    }
    if (!Hive.isAdapterRegistered(FolderModelAdapter().typeId)) {
      Hive.registerAdapter(FolderModelAdapter());
    }

    await Hive.openBox<DocumentModel>(documentsBoxName);
    await Hive.openBox<FolderModel>(foldersBoxName);
  }

  Box<DocumentModel> get _documentsBox => Hive.box<DocumentModel>(documentsBoxName);
  Box<FolderModel> get _foldersBox => Hive.box<FolderModel>(foldersBoxName);

  // --- Document Operations ---

  Future<DocumentModel> createDocument({
    required String title,
    required List<String> imagePaths,
    required String pdfPath,
    String? folderId,
    String extractedText = '',
  }) async {
    final now = DateTime.now();
    final document = DocumentModel(
      id: _uuid.v4(),
      title: title,
      imagePaths: imagePaths,
      pdfPath: pdfPath,
      createdAt: now,
      updatedAt: now,
      folderId: folderId,
      extractedText: extractedText,
    );
    await _documentsBox.put(document.id, document);
    return document;
  }

  DocumentModel? getDocument(String id) {
    return _documentsBox.get(id);
  }

  List<DocumentModel> getAllDocuments() {
    return _documentsBox.values.toList();
  }

  List<DocumentModel> getDocumentsInFolder(String? folderId) {
    return _documentsBox.values.where((doc) => doc.folderId == folderId).toList();
  }

  Future<void> updateDocument(DocumentModel document) async {
    document.updatedAt = DateTime.now();
    await _documentsBox.put(document.id, document);
  }

  Future<void> deleteDocument(String id) async {
    // Note: This only deletes the Hive record.
    // Actual file deletion for images/PDFs should be handled separately if needed.
    await _documentsBox.delete(id);
  }

  // --- Folder Operations ---

  Future<FolderModel> createFolder({
    required String name,
    String? parentFolderId,
  }) async {
    final now = DateTime.now();
    final folder = FolderModel(
      id: _uuid.v4(),
      name: name,
      createdAt: now,
      updatedAt: now,
      parentFolderId: parentFolderId,
    );
    await _foldersBox.put(folder.id, folder);
    return folder;
  }

  FolderModel? getFolder(String id) {
    return _foldersBox.get(id);
  }

  List<FolderModel> getAllFolders() {
    return _foldersBox.values.toList();
  }

  List<FolderModel> getFoldersInParent(String? parentFolderId) {
    return _foldersBox.values.where((folder) => folder.parentFolderId == parentFolderId).toList();
  }

  Future<void> updateFolder(FolderModel folder) async {
    folder.updatedAt = DateTime.now();
    await _foldersBox.put(folder.id, folder);
  }

  Future<void> deleteFolder(String id, {bool deleteContents = false}) async {
    // If deleting contents, also delete all documents and sub-folders.
    // This can be a complex operation and needs careful implementation.
    if (deleteContents) {
      final documentsToDelete = getDocumentsInFolder(id);
      for (final doc in documentsToDelete) {
        await deleteDocument(doc.id); // Consider deleting files too
      }
      final subfoldersToDelete = getFoldersInParent(id);
       for (final subfolder in subfoldersToDelete) {
        await deleteFolder(subfolder.id, deleteContents: true); // Recursive delete
      }
    }
    await _foldersBox.delete(id);
  }

  // --- Search Operations ---
  List<DocumentModel> searchDocuments(String query) {
    if (query.isEmpty) return getAllDocuments();
    final lowerCaseQuery = query.toLowerCase();
    return _documentsBox.values.where((doc) {
      return doc.title.toLowerCase().contains(lowerCaseQuery) ||
             (doc.extractedText.toLowerCase().contains(lowerCaseQuery));
    }).toList();
  }


  // --- Closing ---
  Future<void> close() async {
    // Boxes are automatically closed by Hive if initFlutter is used and app lifecycle is managed.
    // Explicit closing might be needed in specific scenarios or tests.
    // await _documentsBox.close();
    // await _foldersBox.close();
  }
}
